version: '3.4'

services:
  lkf-documentation:
    restart: "no"
    container_name: lkf-documentation
    hostname: lkf-documentation
    image: linkaform/documentation:latest
    build:    
     context: ./
     dockerfile: ./Dockerfile
     target: develop
    volumes:
      - ./:/srv/docs/
      - ./local_build:/usr/local/bin/local_build
      # - ./content:/srv/docs/content
      # - ./extensions:/srv/docs/extensions
      # - ./locale:/srv/docs/locale
    command: sleep infinity
    #command: bash /srv/docs/local_build.sh
    stdin_open: true
    tty: true
